# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/望/program/cpp/lilib3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/望/program/cpp/lilib3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/望/program/cpp/lilib3/CMakeFiles /home/望/program/cpp/lilib3/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/望/program/cpp/lilib3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sample

# Build rule for target.
sample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sample
.PHONY : sample

# fast build rule for target.
sample/fast:
	$(MAKE) -f CMakeFiles/sample.dir/build.make CMakeFiles/sample.dir/build
.PHONY : sample/fast

LongFloat.o: LongFloat.cpp.o

.PHONY : LongFloat.o

# target to build an object file
LongFloat.cpp.o:
	$(MAKE) -f CMakeFiles/sample.dir/build.make CMakeFiles/sample.dir/LongFloat.cpp.o
.PHONY : LongFloat.cpp.o

LongFloat.i: LongFloat.cpp.i

.PHONY : LongFloat.i

# target to preprocess a source file
LongFloat.cpp.i:
	$(MAKE) -f CMakeFiles/sample.dir/build.make CMakeFiles/sample.dir/LongFloat.cpp.i
.PHONY : LongFloat.cpp.i

LongFloat.s: LongFloat.cpp.s

.PHONY : LongFloat.s

# target to generate assembly for a file
LongFloat.cpp.s:
	$(MAKE) -f CMakeFiles/sample.dir/build.make CMakeFiles/sample.dir/LongFloat.cpp.s
.PHONY : LongFloat.cpp.s

LongInterval.o: LongInterval.cpp.o

.PHONY : LongInterval.o

# target to build an object file
LongInterval.cpp.o:
	$(MAKE) -f CMakeFiles/sample.dir/build.make CMakeFiles/sample.dir/LongInterval.cpp.o
.PHONY : LongInterval.cpp.o

LongInterval.i: LongInterval.cpp.i

.PHONY : LongInterval.i

# target to preprocess a source file
LongInterval.cpp.i:
	$(MAKE) -f CMakeFiles/sample.dir/build.make CMakeFiles/sample.dir/LongInterval.cpp.i
.PHONY : LongInterval.cpp.i

LongInterval.s: LongInterval.cpp.s

.PHONY : LongInterval.s

# target to generate assembly for a file
LongInterval.cpp.s:
	$(MAKE) -f CMakeFiles/sample.dir/build.make CMakeFiles/sample.dir/LongInterval.cpp.s
.PHONY : LongInterval.cpp.s

Radius.o: Radius.cpp.o

.PHONY : Radius.o

# target to build an object file
Radius.cpp.o:
	$(MAKE) -f CMakeFiles/sample.dir/build.make CMakeFiles/sample.dir/Radius.cpp.o
.PHONY : Radius.cpp.o

Radius.i: Radius.cpp.i

.PHONY : Radius.i

# target to preprocess a source file
Radius.cpp.i:
	$(MAKE) -f CMakeFiles/sample.dir/build.make CMakeFiles/sample.dir/Radius.cpp.i
.PHONY : Radius.cpp.i

Radius.s: Radius.cpp.s

.PHONY : Radius.s

# target to generate assembly for a file
Radius.cpp.s:
	$(MAKE) -f CMakeFiles/sample.dir/build.make CMakeFiles/sample.dir/Radius.cpp.s
.PHONY : Radius.cpp.s

lilib.o: lilib.cpp.o

.PHONY : lilib.o

# target to build an object file
lilib.cpp.o:
	$(MAKE) -f CMakeFiles/sample.dir/build.make CMakeFiles/sample.dir/lilib.cpp.o
.PHONY : lilib.cpp.o

lilib.i: lilib.cpp.i

.PHONY : lilib.i

# target to preprocess a source file
lilib.cpp.i:
	$(MAKE) -f CMakeFiles/sample.dir/build.make CMakeFiles/sample.dir/lilib.cpp.i
.PHONY : lilib.cpp.i

lilib.s: lilib.cpp.s

.PHONY : lilib.s

# target to generate assembly for a file
lilib.cpp.s:
	$(MAKE) -f CMakeFiles/sample.dir/build.make CMakeFiles/sample.dir/lilib.cpp.s
.PHONY : lilib.cpp.s

sample.o: sample.cpp.o

.PHONY : sample.o

# target to build an object file
sample.cpp.o:
	$(MAKE) -f CMakeFiles/sample.dir/build.make CMakeFiles/sample.dir/sample.cpp.o
.PHONY : sample.cpp.o

sample.i: sample.cpp.i

.PHONY : sample.i

# target to preprocess a source file
sample.cpp.i:
	$(MAKE) -f CMakeFiles/sample.dir/build.make CMakeFiles/sample.dir/sample.cpp.i
.PHONY : sample.cpp.i

sample.s: sample.cpp.s

.PHONY : sample.s

# target to generate assembly for a file
sample.cpp.s:
	$(MAKE) -f CMakeFiles/sample.dir/build.make CMakeFiles/sample.dir/sample.cpp.s
.PHONY : sample.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sample"
	@echo "... LongFloat.o"
	@echo "... LongFloat.i"
	@echo "... LongFloat.s"
	@echo "... LongInterval.o"
	@echo "... LongInterval.i"
	@echo "... LongInterval.s"
	@echo "... Radius.o"
	@echo "... Radius.i"
	@echo "... Radius.s"
	@echo "... lilib.o"
	@echo "... lilib.i"
	@echo "... lilib.s"
	@echo "... sample.o"
	@echo "... sample.i"
	@echo "... sample.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

